version: '3.9'

services:
    py_app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_HOST=mysql_appdb
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=love_calculator
        #volumes:
         #   - app_data:/app
        networks:
            - my_network
        ports:
            - "5000:5000"
        depends_on: 
            - mysql_appdb


    mysql_appdb:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=love_calculator
        networks:
            - my_network
        volumes:
            - mysql_data:/var/lib/mysql
    
networks:
    my_network:
    
volumes:
    app_data:
    mysql_data:

        
